#!/usr/bin/env bash

source "/home/prakhil/scripts/dm-websearch/_dm-helper.sh"
source "/home/prakhil/scripts/dm-websearch/config"


main() {
  # As this is loaded from other file it is technically not defined
  # shellcheck disable=SC2154 # Choosing  a search engine by name from array above.
  engine=$(printf '%s\n' "${!websearch[@]}" | sort | ${DMENU} 'Choose search engine:' "$@") || exit 1

  # Getting the URL of the search engine we chose.
  url="${websearch["${engine}"]}"

  # Searching the chosen engine.
  query=$(echo "$engine" | ${DMENU} 'Enter search query:')

  query="$(echo -n "${query}" | jq -s -R -r @uri)"
  # Display search results in web browser
  # shellcheck disable=SC2154
  ${DMBROWSER} "${url}${query}"
  wmctrl -s 4
}

[[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "$@"
