import = ["/home/prakhil/.config/alacritty/dracula.toml"]
live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 16 

[font.glyph_offset]
x = 0
y = 0

[font.normal]
family = "JetBrainsMono NF"
style = "Regular"

[font.offset]
x = 0
y = 0

[scrolling]
history = 10000
multiplier = 10

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[shell]
program = "/usr/bin/zsh"

[window]
opacity = 0.99

[window.padding]
x = 2
y = 2
