#!/bin/bash
# a script to select output sound device.

choise=$(
  pactl list sinks | awk -F ":" '{if($1 ~ /Sink*/) print $1;else if($1 ~ /Description/) print "#"$2; }' | xargs -L 2 | awk -F "#" '{print $2,$3}'| rofi -dmenu -i -p "sound device"
)
[ -z $choise ] && exit
sink=$(echo $choise | cut -d ' ' -f1)
pactl set-default-sink $sink
