#!/bin/bash
# a script to select output sound device.

sinks=$(pactl list sinks)
# check value in sinks
if [[ ${#sinks} -gt 0 ]]
then
  choise=$(
     echo "$sinks" | awk -F ":" '{if($1 ~ /Sink*/) print $1;else if($1 ~ /Description/) print "#"$2; }' | xargs -L 2 | awk -F "#" '{print $2,$3}'| rofi -dmenu -i -p "sound device"
  )
  [ -z $choise ] && exit

  sink=$(echo $choise | cut -d ' ' -f1)
  pactl set-default-sink $sink
else
  # Error Handling
  notify-send "Connection Failure! Error handling..."
  pulseaudio --kill
  sleep 5
  pulseaudio --start
  notify-send "Restarting pulseaudio"
  sleep 5 
  notify-send "Try selecting the output devices again"
fi
