hwdec=no
vo=gpu

# youtube support
script-opts=ytdl_hook-ytdl_path=/usr/local/bin/yt-dlp
# script-opts=ytdl_hook-ytdl_path=/home/prakhil/.local/bin/yt-dlp
#ytdl-format=bestvideo[height<=?1080][fps<=?60][vcodec!=?vp9]+bestaudio/best
ytdl-format=bestvideo[height<=?1080][fps<=?60][vcodec!=?vp9]+bestaudio/best
#ytdl-format=bestvideo+bestaudio/best
cache=yes
demuxer-max-bytes=200000KiB
demuxer-readahead-secs=30

ytdl-raw-options-append="cookies=~/downloads/yt/cookies.txt"
cookies=yes
cookies-file=~/downloads/yt/cookies.txt
