name: Sync README from index.md

on:
  push:
    paths:
      - "index.md"

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
      - uses: actions/checkout@v3

      - name: Copy index.md to README.md
      - run: cp index.md README.md

      - name: Commit and push
      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com
          git add README.md
          git commit -m "sync README.md" || echo "No changes to commit"
          git push
